backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/images
public_folder: /images/

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    format: json
    folder: "src/data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "home"
        name: "home"
        format: json
        file: "src/data/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - label: "blog"
        name: "blog"
        format: json
        file: "src/data/blog.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - label: "about"
        name: "about"
        format: json
        file: "src/data/about.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - {
              label: "Input Placeholder [name]",
              name: "placeholderName",
              widget: "string"
            }
          - {
              label: "Input Placeholder [email]",
              name: "placeholderEmail",
              widget: "string"
            }
          - {
              label: "Input Placeholder [message]",
              name: "placeholderMessage",
              widget: "string"
            }
          - {
              label: "Submit button text",
              name: "submitButtonText",
              widget: "string"
            }
local_backend: true
